### ISSUE TITLE
No candidate python-magic-bin==0.4.14

### ISSUE THREAD

**Issue by xkortex** [mediaforensics/medifor#26]
Installing the latest mediaforensics/medifor.git fails on python3.6 (tried in local venv and python:3.6-slim-buster), due to (what looks like to me) no viable binary package for linux. 

One of these may be a better alternative:
- [file-magic](https://pypi.org/project/file-magic/) ([github](https://github.com/file/file)) (I think this is the official)
- [filemagic](https://pypi.org/project/filemagic/) ([github](https://github.com/aliles/filemagic))

According to pip search, file DASH magic is the official: 
> file-magic (0.4.0)                       - (official) libmagic Python bindings

But `filemagic` looks slightly better in terms of documentation and CI. 
It would appear that python-magic-bin is a port for win/mac of some sort?

Full trace: 
```shell
$ pip install --verbose 'python-magic-bin'

Collecting python-magic-bin
  1 location(s) to search for versions of python-magic-bin:
  * https://pypi.org/simple/python-magic-bin/
  Getting page https://pypi.org/simple/python-magic-bin/
  Looking up "https://pypi.org/simple/python-magic-bin/" in the cache
  Request header has "max_age" as 0, cache bypassed
  Starting new HTTPS connection (1): pypi.org:443
  https://pypi.org:443 "GET /simple/python-magic-bin/ HTTP/1.1" 304 0
  Analyzing links from page https://pypi.org/simple/python-magic-bin/
    Skipping link https://files.pythonhosted.org/packages/e3/ed/a168a7322693f7ed8d4e7bc85abb45299f2564a1300c8b0bebc6d48b93c2/python_magic_bin-0.4.13-py2.py3-none-macosx_10_6_intel.whl#sha256=2638af65879c8888386e5ad9565d042c6fa71d95f754473935182b62a15cad90 (from https://pypi.org/simple/python-magic-bin/); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/d8/df/dddd9dc69b9ca4f67cbb39d0421fb1e75839564c1c99b530943b04a66fd7/python_magic_bin-0.4.13-py2.py3-none-win32.whl#sha256=562bd2191e980045852e2e7558d8e402670df7020543384cefae4e20526076e5 (from https://pypi.org/simple/python-magic-bin/); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/21/fc/14de77081cacaefa925331de390087f89fe18f94ba537e89473bf34410b1/python_magic_bin-0.4.13-py2.py3-none-win_amd64.whl#sha256=66ba6ae973cf3def146aad792a0022ee831ea10b78b9f2bfd3f6d2db5dd612a2 (from https://pypi.org/simple/python-magic-bin/); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/32/2c/bbe8ad26591745da2c4692ea571145fb027c8ee1a0540407aa327684c4ce/python_magic_bin-0.4.14-py2.py3-none-macosx_10_6_intel.whl#sha256=7b1743b3dbf16601d6eedf4e7c2c9a637901b0faaf24ad4df4d4527e7d8f66a4 (from https://pypi.org/simple/python-magic-bin/); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/5a/5d/10b9ac745d9fd2f7151a2ab901e6bb6983dbd70e87c71111f54859d1ca2e/python_magic_bin-0.4.14-py2.py3-none-win32.whl#sha256=34a788c03adde7608028203e2dbb208f1f62225ad91518787ae26d603ae68892 (from https://pypi.org/simple/python-magic-bin/); it is not compatible with this Python
    Skipping link https://files.pythonhosted.org/packages/07/c2/094e3d62b906d952537196603a23aec4bcd7c6126bf80eb14e6f9f4be3a2/python_magic_bin-0.4.14-py2.py3-none-win_amd64.whl#sha256=90be6206ad31071a36065a2fc169c5afb5e0355cbe6030e87641c6c62edc2b69 (from https://pypi.org/simple/python-magic-bin/); it is not compatible with this Python
  Could not find a version that satisfies the requirement python-magic-bin (from versions: )
Cleaning up...
Removed build tracker '/tmp/pip-req-tracker-xa9852yk'
No matching distribution found for python-magic-bin
Exception information:
Traceback (most recent call last):
  File "/home/mike/.virtualenvs/medifor3/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 179,
in main
    status = self.run(options, args)
  File "/home/mike/.virtualenvs/medifor3/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 315,
in run
    resolver.resolve(requirement_set)
  File "/home/mike/.virtualenvs/medifor3/lib/python3.6/site-packages/pip/_internal/resolve.py", line 131, in resolve
    self._resolve_one(requirement_set, req)
  File "/home/mike/.virtualenvs/medifor3/lib/python3.6/site-packages/pip/_internal/resolve.py", line 294, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/home/mike/.virtualenvs/medifor3/lib/python3.6/site-packages/pip/_internal/resolve.py", line 242, in _get_abstract_dist_for
    self.require_hashes
  File "/home/mike/.virtualenvs/medifor3/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 269, in prepare_linked_requirement
    req.populate_link(finder, upgrade_allowed, require_hashes)
  File "/home/mike/.virtualenvs/medifor3/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 196, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/home/mike/.virtualenvs/medifor3/lib/python3.6/site-packages/pip/_internal/index.py", line 688, in find_requirement
    'No matching distribution found for %s' % req
pip._internal.exceptions.DistributionNotFound: No matching distribution found for python-magic-bin
```

**Comment by xkortex** [comment]
Fixed with d4ccf532ec76a8d59820a0e0e765598e048f56d2
